
#eureka 的端口号

server: 

  port: 1111

#eureka的主机名

eureka: 

  instance: 

    hostname: 192.168.9.81

  client: 

    registerWithEureka: false

    fetchRegistry: false

    serviceUrl: 

      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

   

#eureka的访问地址   